services:
  producer:
    build:
      context: producer
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER
      - SHARED_NAMESPACE=$SHARED_NAMESPACE
  consumer:
    build:
      context: consumer
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER
      - SHARED_NAMESPACE=$SHARED_NAMESPACE
