services:
  chain:
    build:
      context: proxy
    ports:
      - 8080:80
  servicea:
    build:
      context: servicea
    ports:
      - 8080
  serviceb:
    build:
      context: serviceb
    ports:
      - 8080
  servicec:
    build:
      context: servicec
    ports:
      - 8080
